### ISSUE TITLE
Quitar SECRET_KEY y DEBUG=False en los settings

### ISSUE THREAD

**Issue by urkonn** [vaquer/HerramientaFormatosGob#1]
https://github.com/vaquer/HerramientaFormatosGob/blob/master/FormatTools/FormatTools/settings.py#L23-L26

**Comment by vaquer** [comment]
Que quede por variable de ambiente?

**Comment by urkonn** [comment]
si :+1:

**Comment by vaquer** [comment]
Arriba el fix de este issue, las variables de ambiente quedan como SECRET_KEY y DEBUG
